matrix:
  include:
  # GCC 7
  - os: linux
    dist: xenial
    sudo: required
    addons: &gcc7
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-7
        - tree
        - xorg-dev
        - libglu1-mesa-dev
        - libvulkan1
        - libvulkan-dev
        - libopenal1
        - libopenal-dev
    language: cpp
    compiler: gcc
    env:
    - COMPILER=g++-7
    - GSL_CXX_STANDARD=17
    - BUILD_TYPE=Release
    before_install:
    - sudo apt-get update -qq
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
  # Clang 6.0
  - os: linux
    dist: xenial
    sudo: required
    addons: &clang60
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-xenial-6.0
        - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-6.0 main'
          key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
        packages:
        - clang-6.0
        - g++-7
        - tree
        - xorg-dev
        - libglu1-mesa-dev
        - libvulkan1
        - libvulkan-dev
        - libopenal1
        - libopenal-dev
    language: cpp
    compiler: clang
    env:
    - COMPILER=clang++-6.0
    - GSL_CXX_STANDARD=17
    - BUILD_TYPE=Release
    before_install:
    - sudo apt-get update -qq
    - sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-6.0 1000
    - sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-6.0 1000
    - clang --version
  # XCode 10.0
  - os: osx
    osx_image: xcode10
    sudo: required
    language: cpp
    compiler: clang
    env:
    - COMPILER=clang++
    - GSL_CXX_STANDARD=17
    - BUILD_TYPE=Release
    before_install:
    - brew update
    - brew tap caskroom/cask
    - brew install tree
    - brew install openal-soft
    - brew install glfw3 --HEAD
    - brew install cmake || brew upgrade cmake
    - brew cask install apenngrace/vulkan/vulkan-sdk

script:
- cd $TRAVIS_BUILD_DIR
- git submodule update --init --recursive
- mkdir Build
- cd Build
- |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      cmake .. -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=$BUILD_TYPE
    else
      cmake .. -G "Xcode" -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_SHARED_LIBS=OFF
    fi
- tree -d
- |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      make all
    else
      xcodebuild -target Acid -configuration $BUILD_TYPE
    fi
- cd ../
