name: windows_msvc

on: [push, pull_request]

jobs:
  windows_msvc:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Download OpenAL
      run: |
        Invoke-WebRequest -Uri "https://openal-soft.org/openal-binaries/openal-soft-1.20.1-bin.zip" -OutFile openal-soft.zip
        Expand-Archive -Path openal-soft.zip -DestinationPath C:\\
    - name: Download Vulkan
      run: |
        Invoke-WebRequest -Uri "https://sdk.lunarg.com/sdk/download/1.2.135.0/windows/VulkanSDK-1.2.135.0-Installer.exe" -OutFile VulkanSDK.exe
        $installer = Start-Process -FilePath VulkanSDK.exe -Wait -PassThru -ArgumentList @("/S");
        $installer.WaitForExit();
    - name: Build Acid
      env:
        VULKAN_SDK: "C:\\VulkanSDK\\1.2.135.0"
        OPENALDIR: "C:\\openal-soft-1.20.1-bin"
      run: |
        cmake -B Build -G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE=Release
        cmake --build Build